config:
  exp_name: afa_dla_up_dla34_bsds500_pascal

  dataset: bsds500
  bsds_with_pascal: true
  is_edge: true

  crop_size: "416,416"

  accelerator: gpu
  devices: 4
  strategy: ddp
  samples_per_gpu: 4
  workers_per_gpu: 4

  sync_batchnorm: true
  precision: 16
  benchmark: true
  replace_sampler_ddp: false

  lr_scheduler: step
  step_epochs: "10,16"
  lr: 0.01
  max_epochs: 20
  pos_weight: 10.

  arch: afa_dla_seg.dla34
  num_sanity_val_steps: 0
  check_val_every_n_epoch: 21
  pbar_refresh_rate: 50
