config:
  exp_name: afa_dla_up_ocr_ssr_dla102x_cityscapes_cv_3

  dataset: cityscapes
  cv: 3

  crop_size: "1024,1024"

  accelerator: gpu
  devices: 8
  strategy: ddp
  samples_per_gpu: 2
  workers_per_gpu: 4

  sync_batchnorm: true
  precision: 16
  benchmark: true
  replace_sampler_ddp: false

  poly_exp: 0.9
  lr: 0.015
  max_epochs: 275
  max_cu_epochs: 250
  warmup_iters: 1000

  n_scales_training: "0.5,1.0"
  n_scales_inference: "0.5,1.0,1.5,1.75,2.0"

  arch: afa_dla_ocr_seg_ssr.dla102x
  num_sanity_val_steps: 0
  check_val_every_n_epoch: 25
