config:
  exp_name: afa_dla_up_dla34_nyud_hha

  dataset: nyud
  nyud_input_type: "hha"
  is_edge: true

  crop_size: "480,480"

  accelerator: gpu
  devices: 4
  strategy: ddp
  samples_per_gpu: 4
  workers_per_gpu: 4

  sync_batchnorm: true
  precision: 16
  benchmark: true
  replace_sampler_ddp: False

  lr_scheduler: step
  step_epochs: "30,46"
  lr: 0.01
  max_epochs: 54
  pos_weight: 10.

  arch: afa_dla_seg.dla34
  num_sanity_val_steps: 0
  check_val_every_n_epoch: 55
