config:
  exp_name: afa_dla_up_ocr_ssr_dla169_bdd100k

  dataset: bdd100k

  crop_size: "720,1280"
  class_uniform_tile: 720

  accelerator: gpu
  devices: 8
  strategy: ddp
  samples_per_gpu: 2
  workers_per_gpu: 4

  sync_batchnorm: true
  precision: 16
  benchmark: true
  replace_sampler_ddp: false

  poly_exp: 0.9
  lr: 0.015
  max_epochs: 200
  warmup_iters: 1000

  n_scales_training: "0.5,1.0"
  n_scales_inference: "0.5,1.0,1.5,2.0"

  arch: afa_dla_ocr_seg_ssr.dla169
  num_sanity_val_steps: 0
  check_val_every_n_epoch: 20
